baseURL = "https://frosty-borg-6b0305.netlify.com/"
languageCode = "en-us"
title = "Rimvydas Zilinskas Resume"

theme = "resume"

[params]
    firstName = "Rimvydas"
    lastName = "Zilinskas"
    address = "Copenhagen, Denmark"
    phone = "+45 27 28 01 36"
    contactNote = "Developer"
    email = "rimvydas.zilinskas@yahoo.com"
    description = "Junior Software Developer"
    profileImage = '/profile.jpg'

    showSkills = true
    showPorjects = true
    showOpenSource = false
    showPublications = false
    showExperience = true
    showEducation = true
    showQR = true
    showBlog = true

    gitCommitPrefix = "https://github.com/YOURNAME/REPONAME/commit/"


[[params.handles]]
    name = "LinkedIn"
    link = "https://linkedin.com/in/rzilinskas/"

[[params.handles]]
    name = "GitHub"
    link = "https://github.com/rimvydaszilinskas/"

[outputs]
    home = ["HTML", "JSON"]